# Builder AI Configuration

# Refer to the official Builder AI documentation at:
# https://CodefiLabs.com/builder-ai

agent_os_version: 1.4.1

agents:
  claude_code:
    enabled: false
  cursor:
    enabled: false

project_types:
  default:
    instructions: ~/.builder-ai/instructions
    standards: ~/.builder-ai/standards

  # type_a:
  #   instructions: ~/.builder-ai/project_types/type_a/instructions
  #   standards: ~/.builder-ai/project_types/type_a/standards

  # type_b:
  #   instructions: ~/.builder-ai/project_types/type_b/instructions
  #   standards: ~/.builder-ai/project_types/type_b/standards

default_project_type: default
